### ISSUE TITLE
Just add this to the anything.js library

### ISSUE THREAD

**Issue by eorroe** [TheBinaryBee/hohoho.js#1]
[Anything.js](https://github.com/Rabrennie/anything.js)

**Comment by TheBinaryBee** [comment]
Nice, thanks for including hohoho.js :+1:

**Comment by eorroe** [comment]
Huh? I didn't add it, I was suggesting to add it Anything.js

**Comment by TheBinaryBee** [comment]
I yeah sorry my bad! I thought you were the owner of the repo!

I submited it now.

**Comment by eorroe** [comment]
Nope, but cool
